### ISSUE TITLE
Set Daw control to move regardless of current selection

### ISSUE THREAD

**Issue by maxcloutier13** [maxcloutier13/Akai-MPK261-AbletonLive-MIDIRemoteScript#4]
Change clip and track regardless of anything.
Better than keystrokes left/right...

**Comment by prg318** [comment]
Hi!
I know this is closed, but I wanted to follow up about it to see if you had any ideas for getting this working on a MPK249.  I'm following the instructions in the README, but I can't get Ableton to change track or clip in response to CC values.  Does anything need to be done in Ableton so that it knows to change track/preset on the specified ch1 CC values? I don't see anything in the MPK261MX.py script that adds any mapping for these.

I've checked in MIDI-OX and it looks like my DAW control keys are generating the right events:

```
 TIMESTAMP IN PORT STATUS DATA1 DATA2 CHAN NOTE EVENT               
 Opened MIDI Input
 000006FE   1  --     B0    15    7F    1  ---  CC: 21 (E-MU)         
 00000783   1  --     B0    15    00    1  ---  CC: 21 (E-MU)         
```
I have my daw control keys set like this (DAWRight in this example):
```
DAWRight
Type: CC
MIDIChannel: USB A1
CC Number: 021
MIDI to DIN: Off
Mode: Momentary
Invert: off
```

Thanks again for these scripts - they've worked mostly out of the box for me on my MPK249!
